# Generated by Django 6.0.7 on 2026-07-26 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('title', models.CharField(max_length=300)),
                ('poster_path', models.URLField(blank=True, null=True)),
                ('total_episodes', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('plan_to_watch', 'Plan to Watch'), ('watching', 'Watching'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='plan_to_watch', max_length=20)),
                ('current_episode', models.IntegerField(default=0)),
                ('user_rating', models.FloatField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'watchlist_items',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'tmdb_id')},
            },
        ),
    ]
