# Generated by Django 6.0.7 on 2026-08-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlistitem',
            name='season_progress',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
